import {Constants} from '../common-module/Constants'

export class CardApi {
  static getAllGenderDetailsUrl = Constants.baseUrl + 'cardholder-service/getAllGenderDetails'
  static getCardHolderRoleListUrl = Constants.baseUrl + 'cardholder-service/getCardHolderRoleList'
  static getCarrierListUrl = Constants.baseUrl + 'cardholder-service/getCarrierList'
  
  static getCompanyDetailByCompanyCoKey= Constants.baseUrl + 'company-service/getCompanyDetailByCompanyCoKey';
  static saveCardUrl= Constants.baseUrl + 'card-service/saveCardDetails';
  static getCompanyPlanUrl = Constants.baseUrl + 'company-service/getCompanyPlansByCombineId';
  static getAutogeneratedCardNumbersUrl = Constants.baseUrl + 'card-service/getAutoCardNumbers';
  static checkCardDetailExistByCardIdUrl = Constants.baseUrl + 'card-service/checkCardDetailByCardId';
  static updateCardDetailsUrl = Constants.baseUrl + 'card-service/updateCardDetails';
  static addUpdateStudentHistoryUrl = Constants.baseUrl + 'card-service/addUpdateCardHolderPersonStudentHistory';
  static isCompanyPostalcodeValidUrl = Constants.baseUrl + 'company-service/getPostalDetail';
  static isCompanyCityProvinceCountryValidUrl = Constants.baseUrl + 'company-service/verifyPostalDetail';
  static terminateCardUrl = Constants.baseUrl + 'card-service/terminateCard';
  static activateCardUrl = Constants.baseUrl + 'card-service/activateCard';

  /*card comment API*/
  static getCardCommentsByCardIdUrl = Constants.baseUrl + 'card-service/getCardCommentsByCardId'; 
  static updateCardCommentsUrl = Constants.baseUrl + 'card-service/updateCardComments';
  static saveCardCommentsUrl = Constants.baseUrl + 'card-service/saveCardComments';
  
  /**
   * Card Holder Api Start
   */
  static saveCardholderUrl = Constants.baseUrl + 'cardholder-service/addCardholder';
  static updateCardholderUrl = Constants.baseUrl + 'cardholder-service/updateCardholder';
  static getCardHolderdetailById = Constants.baseUrl + 'cardholder-service/findCardHolder';  
  static deleteCardHolderById = Constants.baseUrl + 'cardholder-service/deleteCardHolder';  
  static getCardHolderList = Constants.baseUrl + 'cardholder-service/getCardHolderList';  
  static getCardHolderListByCardId = Constants.baseUrl + 'cardholder-service/getCardHolderListByCardId';  
  static terminateCardHolder = Constants.baseUrl + 'cardholder-service/terminateCardHolder'; 
  static getCardHolderComments = Constants.baseUrl + 'cardholder-service/getCardHolderComments';  
  static addUpdateCardHolderSingleComments = Constants.baseUrl + 'cardholder-service/addUpdateCardHolderSingleComments'; 
  static addOrUpdateTrusteeUrl = Constants.baseUrl + 'cardholder-service/addOrUpdateTrustee'; 
  static addUpdateCardHolderPersonStudentHistoryUrl = Constants.baseUrl + 'cardholder-service/addUpdateCardHolderPersonStudentHistory'; 
  static activateCardHolderUrl = Constants.baseUrl + 'cardholder-service/activateCardHolder';

  /**
   * Card Holder Api End
   */
 
  static getCardDetails = Constants.baseUrl + 'card-service/getCardDetails'

  /**
   * Card Holder History Datatable
   */
  static getCardHolderRoleAssignHisorytUrl = Constants.baseUrl + 'cardholder-service/getCardHolderRoleAssignHistList';
  static getCardHolderCobHistoryUrl = Constants.baseUrl + 'cardholder-service/getCardHolderCobHistList';
  static getCardHolderEligibilityListUrl = Constants.baseUrl + 'cardholder-service/getCardHolderEligibilityList';
  static getVoucherByIdUrl = Constants.baseUrl + 'cardholder-service/getVoucher';
  static getVoucherListUrl = Constants.baseUrl + 'cardholder-service/getAllVouchers';
  static getExpenseAdjustmentsByCardHolderKeyUrl = Constants.baseUrl + 'cardholder-service/getExpenseAdjustmentsByCardHolderKey';
  static saveUpdateCardHolderRoleAssignmentUrl = Constants.baseUrl + 'cardholder-service/addUpdateCardHolderRoleAssignment';
  static saveUpdateCardHolderCobHistoryUrl = Constants.baseUrl + 'cardholder-service/addUpdateCardHolderCobHistory';
  static addCardHolderVoucherUrl = Constants.baseUrl + 'cardholder-service/addVoucher';
  static updateCardHolderVoucherUrl = Constants.baseUrl + 'cardholder-service/updateVoucher';
  static addOrUpdateVoucherUrl = Constants.baseUrl + 'cardholder-service/addOrUpdateVoucher';
  static addUpdateHolderEligibilityHistoryUrl = Constants.baseUrl + 'cardholder-service/addUpdateHolderEligibilityHistory';
  static deleteCardHolderVoucherUrl = Constants.baseUrl + 'cardholder-service/deleteVoucher';
  static addExpenseAdjustmentUrl = Constants.baseUrl + 'cardholder-service/addExpenseAdjustment';
  static updateExpenseAdjustmentUrl = Constants.baseUrl + 'cardholder-service/updateExpenseAdjustment';
  static deleteStudentHistoryUrl = Constants.baseUrl + 'cardholder-service/deleteCardHolderPersonStudentHistory';
  static getTrusteeUrl = Constants.baseUrl + 'card-service/getTrustee';
  static deleteCardHolderPersonStudentHistoryUrl = Constants.baseUrl + 'cardholder-service/deleteCardHolderPersonStudentHistory';
  static checkCardHolderRoleUrl = Constants.baseUrl + 'cardholder-service/checkCardHolderRole';
  
  //Card Popups Api
  static getCardEligibiltyHistory = Constants.baseUrl + 'card-service/getCardEligibiltyHistory';
  static getCardContactHistory = Constants.baseUrl + 'card-service/getCardContactHistory';
  static getCardBankAccountHistory = Constants.baseUrl + 'card-service/getCardBankAccountHistory';
  static getCardTypeHistory = Constants.baseUrl + 'card-service/getCardTypeHistory';
  static getExtraBenefitListByCard = Constants.baseUrl + 'card-service/getExtraBenefitListByCard';
  static saveAndUpdatecardBenefitHistUrl = Constants.baseUrl + 'card-service/saveAndUpdatecardBenefitHist';
  static saveCardEligibilityUrl = Constants.baseUrl + 'card-service/saveCardEligibility';
  static saveCardContactUrl = Constants.baseUrl + 'card-service/saveCardContact';
  static saveCardBankAccountUrl = Constants.baseUrl + 'card-service/saveCardBankAccount';

  /* Search card Api */
  static getCardSearchByFilter= Constants.baseUrl + 'card-service/getCardSearchByFilter';
  static getCardSearchByGridFilter= Constants.baseUrl + 'card-service/getCardSearchByGridFilter';
  
}